#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xF54984BFA16C640F (glennrp+bmo@gmail.com)
#
Name     : pngcrush
Version  : 1.8.13.nolib
Release  : 1
URL      : https://sourceforge.net/projects/pmt/files/pngcrush/1.8.13/pngcrush-1.8.13-nolib.tar.gz
Source0  : https://sourceforge.net/projects/pmt/files/pngcrush/1.8.13/pngcrush-1.8.13-nolib.tar.gz
Source1  : https://sourceforge.net/projects/pmt/files/pngcrush/1.8.13/pngcrush-1.8.13-nolib.tar.gz/download
Source2  : https://sourceforge.net/projects/pmt/files/pngcrush/1.8.13/pngcrush-1.8.13-nolib.tar.gz.asc
Summary  : No detailed summary available
Group    : Development/Tools
License  : X11
Requires: pngcrush-bin = %{version}-%{release}
BuildRequires : libpng-dev
BuildRequires : zlib-dev

%description
No detailed description available

%package bin
Summary: bin components for the pngcrush package.
Group: Binaries

%description bin
bin components for the pngcrush package.


%prep
%setup -q -n pngcrush-1.8.13-nolib
cd %{_builddir}/pngcrush-1.8.13-nolib
cd ..
%setup -q -T -n pngcrush-1.8.13-nolib -b 1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1579295898
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
make  %{?_smp_mflags}


%install
export SOURCE_DATE_EPOCH=1579295898
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/pngcrush
